version: '3.8'

networks:
  my_bridge_network2:
    driver: bridge

services:
  # 主服务（通过环境变量控制实例数）
  sxgf-python:
    image: sxgf_img:v2025-03-07
    hostname: sxgf_python
    deploy:
      replicas: 3  # 初始实例数，可通过命令动态调整
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 2
      resources:
        limits:
          memory: 10G
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - TZ=Asia/Shanghai
    volumes:
      - /home/nfs/datas:/opt/test
      - /home/nfs/:/nfs
    privileged: true
    command: /bin/bash -c "bash /nfs/sxgf_python/app.sh"
    networks:
      - my_bridge_network2

  # Nginx 负载均衡器
  nginx-lb:
    image: docker.1ms.run/nginx:1.27.4-alpine3.21
    ports:
      - "5006:80"  # 对外暴露端口（原5006映射到Nginx的80）
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - sxgf-python
    networks:
      - my_bridge_network2