name: Upload to COS

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository main branch
      uses: actions/checkout@v2
      with: 
        ref: 'main'
        submodules: true
        
    - name: Use Node.js 16
      uses: actions/setup-node@v4
      with:
        # Examples: 20, 18.19, >=16.20.2, lts/Iron, lts/Hydrogen, *, latest, current, node
        # Ref: https://github.com/actions/setup-node#supported-version-syntax
        node-version: '22.5.1'
        
    - name: Cache NPM dependencies
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.OS }}-npm-cache
        restore-keys: |
          ${{ runner.OS }}-npm-cache
          
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist
        
    - name: Deploy to Tencent COS
      env:
        SECRET_ID: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
        SECRET_KEY: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
        BUCKET: ${{ secrets.COS_BUCKET }}
        REGION: ${{ secrets.COS_REGION }}
      run: |
        pip install coscmd
        echo ${SECRET_ID} 
        echo ${SECRET_KEY}
        echo ${BUCKET}
        echo ${REGION}
        # coscmd upload -rs --delete ./dist/ / -f
