name: Upload to COS

on: [push]

jobs:
  build:

    runs-on: "ubuntu-20.04"

    steps:
    - name: Checkout Repository main branch
      uses: actions/checkout@v2
      with: 
        ref: 'main'
        submodules: true
        
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        # Examples: 20, 18.19, >=16.20.2, lts/Iron, lts/Hydrogen, *, latest, current, node
        # Ref: https://github.com/actions/setup-node#supported-version-syntax
        node-version: '22.5.1'
        
    - name: Cache NPM dependencies
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.OS }}-npm-cache
        restore-keys: |
          ${{ runner.OS }}-npm-cache
          
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build

    - name: Install coscmd
      run: sudo pip3 install coscmd
      
    - name: Deploy to Tencent COS
      env:
        SECRET_ID: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
        SECRET_KEY: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
        BUCKET: ${{ secrets.COS_BUCKET }}
        REGION: ${{ secrets.COS_REGION }}
      run: |
       coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION

    - name: Upload
      run: coscmd upload -rs --skipmd5 dist/  / 
