name: Upload to COS

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository main branch
      uses: actions/checkout@v2
      with: 
        ref: 'main'
        submodules: true
        
    - name: Use Node.js 16
      uses: actions/setup-node@v4
      with:
        # Examples: 20, 18.19, >=16.20.2, lts/Iron, lts/Hydrogen, *, latest, current, node
        # Ref: https://github.com/actions/setup-node#supported-version-syntax
        node-version: '22.5.1'
        
    - name: Cache NPM dependencies
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.OS }}-npm-cache
        restore-keys: |
          ${{ runner.OS }}-npm-cache
          
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist
        
    - name: Install coscmd
      run: pip install coscmd
    - name: Configure coscmd
      env:
        SECRET_ID: ${{ secrets.SecretId }}
        SECRET_KEY: ${{ secrets.SecretKey }}
        BUCKET: pkcile-1301890641
        REGION: ap-shanghai
      run: coscmd config -a ${SECRET_ID} -s ${SECRET_KEY} -b ${BUCKET} -r ${REGION}
      
    - name: Upload
      run: coscmd upload -rs --delete ./dist/ / -f --ignore "./.git/*"
